### ISSUE TITLE
Question about computed compatibility on generic types

### ISSUE THREAD

**Issue by surli** [revapi/revapi#107]
I just saw in Spoon the recent following change: 

| Name | Change 1 |
| :---: | :---: |
| Old | method DefaultJavaPrettyPrinter::computeImports(CtType) |
| New | method DefaultJavaPrettyPrinter::computeImports(CtType) |
| Code | java.method.returnTypeTypeParametersChanged |
| Description | The return type changed from 'java.util.Collection<spoon.reflect.reference.CtReference>' to 'java.util.Collection<spoon.reflect.reference.CtImport>'. |
| Breaking | binary: non_breaking,  |

and I wonder why revapi is considering it as `non_breaking`. Note that here there is no inheritance relation between `CtImport` and `CtReference`.
I suppose that when considering binaries, revapi does not check the generics, am  I right? Or is it an issue?

**Comment by metlos** [comment]
This problem is breaking source compatibility and usually also semantic compatibility. But it is a binary compatible change because of type erasure. At runtime, the return type is merely `java.util.Collection` and the implicit casts are done on the caller sites (which is the point where it would usually break).

**Comment by surli** [comment]
> Binary compatibility means that you will be able to link existing code with the new, binary compatible, library version. It does not at all mean that stuff won't break ;)

Thanks for the explanation: that was my intuition but I wanted to be sure :)
