### ISSUE TITLE
Uncaught serialVersionUID change

### ISSUE THREAD

**Issue by rfer** [revapi/revapi#120]
Hi,

I've just bumped into a particular case where a supposedly breaking change wasn't caught. Which should have, because this eventually caused a serialVersionUID mismatch.

The change in question is the following:

`private static final String STATIC_STRING = "com.example.NameOfClass";`

changed to:

`private static final String STATIC_STRING = NameOfClass.class.getName();`

So two questions here:

- Shouldn't this have been caught?
- Isn't there any way that we could forcefully check for serialVersionUID changes?

**Comment by metlos** [comment]
Hi, thanks for reporting this!

I've just added the `java.field.serialVersionUIDChanged` check that I somehow managed to miss out.

Now for your questions. A change in a static private field should not change the serialization behavior
even though a different default `serializationVersionUID` value would be computed because of that change.

I've recently changed the default behavior of the `serialVersionUID` changes to only react on structural changes and not on the changes of the default computed value for the field. I.e. the problems are reported only if the class really changes structurally (i.e. fields change in numbers or types). See https://revapi.org/modules/revapi-java/index.html#field_code_serialversionuid_code_unchanged

So in another words - if you use the default generated `serialVersionUID`s in your codebase, you may want to reconfigure revapi to use the "jvm" `changeDetection` for the serialVersionUID-related checks.

**Comment by metlos** [comment]
Fixed in `revapi-java-0.16.0`.

**Comment by dspereira004** [comment]
Hi @metlos,

It seems that both _java.field.serialVersionUIDChanged_ and _java.field.serialVersionUIDUnChanged_ only work on files that contain **serializationVersionUID**. Am I right?

I'm saying this because I think that something nice to have is to catch breaking changes (or potential ones) of classes that implement _Serializable_ **but** do not have the **serializationVersionUID** defined. If classes somehow change, they might be incompatible with their previous version.

**Comment by dspereira004** [comment]
Unfortunately, I will not have time in the near future to do this change; if this situation changes, I will let you know and implement the feature
