### ISSUE TITLE
Revapi is resolving the wrong dependency version

### ISSUE THREAD

**Issue by tmortagne** [revapi/revapi#129]
revapi version: 0.10.1

It's as if revapi was picking the wrong dependency version when doing the comparison but I can't figure out why be looking at mvn dependeny:tree. What is special about this dependency is that it's a scope provided.

You can reproduce by building https://github.com/xwiki/xwiki-platform/tree/master/xwiki-platform-core/xwiki-platform-wysiwyg/xwiki-platform-wysiwyg-api with `mvn clean install -Pquality`.

From what I understand revapi resolve that xwiki-platform-wysiwyg-api 10.3 depending on servlet 3.0.1 as expected but for some reason with the current version it uses servlet 2.x (not really sure which one) but I have no idea how it can end up with this version since mvn dependency:tree mention 3.0.1 only. The result is that it's complaining about changes in MutableServletRequest which implements javax.servlet.ServletRequest.

**Comment by metlos** [comment]
I added some debug logging during the artifact resolution so that this is more obvious in the future.

From the new debug logs, it can be deduced that:
`org.xwiki.commons:xwiki-commons-xml:jar:10.4-SNAPSHOT` depends on `org.apache.commons:commons-dbcp2:jar:2.2.0` which in turn depends on `javax.servlet:servlet-api:jar:2.4` as a provided dependency.

**Comment by metlos** [comment]
Now the question is whether Revapi should be the tool that would catch such things.

The reason why revapi crawls even the provided dependencies is that because they *can* contribute to the API if the user of the dependency uses a class from the provided dependency in its API. That is a bad design decision but it can happen.

But it can lead to Revapi reporting these false positives that are, for better or worse, ephemeral in nature because they depend on the order revapi processes the dependencies while establishing the class tree.

So while I think we found a real dependency issue in your codebase, it was done by accident and in the end of the day revapi shouldn't IMHO be the tool for doing this.

The "proper" way of catching these kinds of problems in much more sophisticated because IMHO it should involve usage scan of individual classes throughout the codebase and the code of dependencies to establish, e.g. whether `commons-dbcp2` even can break given it will be provided `servlet-api-3.0.1` and given the calls you're making to it from your codebase.

**Comment by metlos** [comment]
So I think I will change the artifact resolution to that of maven - include compile and provided dependencies of the main artifact and only compile dependencies transitively.

**Comment by metlos** [comment]
Thanks for reporting this. Super interesting stuff and ideas for the future :)

**Comment by tmortagne** [comment]
> So I think I will change the artifact resolution to that of maven - include compile and provided dependencies of the main artifact and only compile dependencies transitively.

Thanks !

**Comment by metlos** [comment]
Btw. to work around the issue, you can set the "resolveProvidedDependencies" parameter of the revapi-maven-plugin to false (https://revapi.org/modules/revapi-maven-plugin/check-mojo.html#resolveProvidedDependencies).

That will cause no provided deps to be included in the checked archives, which btw. is actually quite good, because that will flag any classes from the provided deps that leak into the API as missing..

**Comment by tmortagne** [comment]
> That will cause no provided deps to be included in the checked archives, which btw. is actually quite good, because that will flag any classes from the provided deps that leak into the API as missing..

Well it depends, servlet API is a `provided` dependency because it's application job server to provide it (you even get an error if you package a servlet JAR in your WAR) and not because you may not have it at runtime so failing APIs located in xwiki-platform-container-servlet for example just because they expose classes coming from a provided dependency (unless I misunderstood what you meant) is not great for us either.

**Comment by metlos** [comment]
> > That will cause no provided deps to be included in the checked  archives, which btw. is actually quite good, because that will flag any  classes from the provided deps that leak into the API as missing.. 

> Well it depends, servlet API is a provided dependency  because it's application job server to provide it (you even get an error  if you package a servlet JAR in your WAR) and not because you may not  have it at runtime so failing APIs located in  xwiki-platform-container-servlet for example just because they expose  classes coming from a provided dependency (unless I misunderstood what  you meant and this property is only related to transitive dependencies)  is not great for us either.

True. In that case you'll have to wait for the new release of the maven plugin which should fix this. I'll try my best to get to it today, but I can't promise.

**Comment by tmortagne** [comment]
It's already great that you are working on it :)

**Comment by vmassol** [comment]
Hi Lukas,

Any progress by any chance (no pressure)? :)

FTR just saw this commit on xwiki side: 
https://github.com/xwiki/xwiki-platform/commit/9f95c7f881507abe2afee57b139e52ba4b22abec

**Comment by metlos** [comment]
Heh, sorry, real life intervenes :wink: I will probably get to this next week...

**Comment by vmassol** [comment]
No worries Lukas. Thanks again

**Comment by metlos** [comment]
Should be fixed in `revapi-maven-plugin-0.10.2`.

**Comment by vmassol** [comment]
Thanks Lukas! I'll upgrade now :)

**Comment by tmortagne** [comment]
Thanks :)

**Comment by metlos** [comment]
Btw. you can follow https://twitter.com/revapi_org. I put the release announcements there...

**Comment by vmassol** [comment]
thanks for the twitter info, didn't know. Now following you ;)
