### ISSUE TITLE
Exporting differences to JSON

### ISSUE THREAD

**Issue by realityforge** [revapi/revapi#144]
I want to get the differences between two releases in a json format the same as the online tool. So essentially something like

https://diff.revapi.org/check?old=org.realityforge.arez%3Aarez-core%3A0.110&new=org.realityforge.arez%3Aarez-core%3A0.127

I am doing this before the project has been released, as part of the release process so at best there is a local file that has just been built representing one of the libraries.

That json file will ultimately be checked in as part of the release and will also have custom data crunching run over it and may drive a report.

I assume there is an easy way of doing this given that it is already available via the Web API. Any pointers?

**Comment by metlos** [comment]
Heh, the backend of diff.revapi.org is the only piece that's not open source, but there's really not much to it :)

The backend runs Revapi with the following configuration:
```json
[
  {
    "extension": "revapi.java",
    "configuration": {
      "missing-classes": {
        "behavior": "ignore",
        "ignoreMissingAnnotations": true
      },
      "reportUsesFor": "all-differences"
    }
  },
  {
    "extension": "revapi.ignore",
    "configuration": [
      {
        "code": "java.annotation.attributeValueChanged",
        "annotationType": "scala.reflect.ScalaSignature"
      }
    ]
  }
]
```
and uses a reporter very similar to https://github.com/revapi/revapi/blob/master/revapi-java/src/test/java/org/revapi/java/AbstractJavaElementAnalyzerTest.java#L308 and then just access that and converts all the found reports into JSON manually.

Which is NOT the canonical way of doing it actually, but that's what you get when you're doing it late at night and don't expect others to see it :wink:

To implement it properly so that it blends nicely into maven plugin et al., you should write a new reporter extension, which should actually be quite simple... Take a look for example at https://github.com/revapi/revapi/blob/master/revapi-reporter-text/src/main/java/org/revapi/reporter/text/TextReporter.java. If you ignore the slightly complex initialization (which you can mostly remove in your case), it actually is not more than 80 lines of code or so.

You'd do something very similar. You would keep the configuration for specifying the output, maybe even the config for the minimum severity of the differences and just change what you write into the file.

Would be awesome if you could share your work then, I think this would be appreciated by more users.

**Comment by realityforge** [comment]
Thanks - that is certainly enough to get me started. Thanks!

**Comment by realityforge** [comment]
Thanks for your help. I ended up putting together a simple tool to do all I needed.

See https://github.com/realityforge/revapi-diff

Anyhoo - now it is time to wander off and write tools to process the json.

Thanks again for the awesome tool.
