### ISSUE TITLE
Both way to use interfaces

### ISSUE THREAD

**Issue by sbernard31** [revapi/revapi#174]
In java, It seems to me there is both way to use interface for API.

1. as callback interface, where it is intended that users provide their own implementations. 
2. as "functionality expose interface", where it is **not** intended that users provide their own implementation and implementation is always created by the library itself.

For 1. we can not add new method without breaking the API (java.method.addedToInterface) but For 2. adding an new method should not be consider as an API break.

I know that I can create an exception using configuration.
But I ask myself if the is a more straightforward way as this sounds to be a common usage case.
Maybe something like annotate an interface as a @facade. (which has the advantage to also document the code)

Maybe my problem is that I use interface in a bad way and I should rather use the real facade design pattern which uses `class` instead of `interface` and in this case there is no more issue, but I'm not sure this is always doable. (e.g. for factory pattern this does work).

WDYT ?

**Comment by metlos** [comment]
You are certainly right. There are interfaces that are meant to be implemented by callers of your code, i.e. your SPI, and there can be interfaces that you provide to users that are really meant to be "facades" hiding the real implementation that is private to your module - i.e. you provide the implementation to your users and don't expect users to implement the interface.

Java language as such doesn't make that distinction though, so it's impossible for tools like Revapi to realize the distinction without some help.

It's long overdue due to real-life interventions but I'm working on enabling configuration like "ignore all problems on all elements of a class annotated by `@Facade`" but that work is not yet finished. For now, you just need to ignore the problems that are really not problems due to the assumed usage of the interface more or less individually.

**Comment by metlos** [comment]
Btw, take a look at https://revapi.org/modules/revapi-java/index.html#filtering_based_on_annotations - maybe it already can cover your use case.

**Comment by sbernard31** [comment]
Thx for your detailed answer :)

About `filtering_based_on_annotations`, I read the documentation and if I understand correctly this just allow to include or exclude element from the API.  For the `facade` feature this is more about keeping it in the API but ignore some errors (like `addedToInterface`).

This make me think : do you plan to also provide some "common" annotation with default configuration?

Like : 
 - `@Public` => means includes to the API
 - `@Private` => means excludes from the API
 - `@Facade` => ignore `addedToInterface` error (and probably others)

(And probably others ...)
This would make very easy the usage of revapi for common use cases.
 
There is maybe an issue with this idea. I'm not an expert about Annotation, but this means that projects should inherit from a `org.revapi.annotation` project to be able to use this annotation in their code. I don't know if this is a good idea :thinking:

Or maybe instead using annotation this should be better to use javadoc tag ? (I don't know if there are easily accessible for you). 
- First advantage you can add it even if there are not declared.
- Second advantage you can imagine that revapi provide taglet which will be used to generate javadoc. (see [taglet in java](https://docs.oracle.com/javase/7/docs/technotes/guides/javadoc/taglet/overview.html) and add [taglet to maven](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#tagletArtifacts)) e.g. @Facade will explain that this interface should not be inherited.
- Third some warning could be raised about missing "@since" [like API Tools do](https://help.eclipse.org/2019-12/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Freference%2Fapi-tooling%2Fapi_since_tags.htm)

**Comment by metlos** [comment]
It might be an interesting idea, but it's not something I would point my immediate attention to. There are bigger fish to fry here :)

I would love to discuss any proposals you might have in mind, so don't hesitate to raise a new issue with such proposals.

For now, I'm closing this issue because I believe we've found a common ground.
