### ISSUE TITLE
More information about externalClassExposedInAPI ?

### ISSUE THREAD

**Issue by sbernard31** [revapi/revapi#186]
I'm not sure to really understand the point with [External Class Exposed In API](https://revapi.org/modules/revapi-java/differences.html#a_external_class_exposed_in_api)

> This is reported for classes from dependencies that are exposed in the API (for example as a return value). This is generally discouraged practice because it makes updating the dependency version a more complex task (you want a bugfix but you don’t want the changed API to leak to your users).

Could you help me to better understand it ?

**Comment by metlos** [comment]
Well, this basically serves as a warning to the user - you're requiring your callers to use a class from your dependency. Are you sure you intend to do that?

Surely, there are very valid reasons for doing it and in those cases you can configure revapi to ignore such occurrences. But other times you might do this by accident - say you internally depend on guava and you changed one of your API methods to use its `ImmutableSet`.

I think you need to be conscious about that decision, because with that change you made it hard for yourself to upgrade the guava version, because if `ImmutableSet` changes incompatibly, you potentially broke the code of all your callers, not just yours.

**Comment by sbernard31** [comment]
Thx a lot for the explanation. It's clearer to me but : 

> you're requiring your callers to use a class from your dependency

In my case I have a multi-module project.
And I have a `core` module and several `specific` module which depends on this core module. The core module contains several classes which are exposed in specific module.
I never get any complains about revapi. 

And recently I add a new class in core (in a minor version) which is exposed in 1 specific module. (all module have their minor version increased)
It seems that only the new addition is considered as a problem, I don't get why ?

The concrete case is available [here](https://github.com/eclipse/leshan/pull/858) and give this error : 
```
The following API problems caused the build to fail:
[INFO] java.class.externalClassExposedInAPI: class org.eclipse.leshan.core.request.BootstrapDiscoverRequest: A class from supplementary archives is used in a public capacity in the API. (breaks semantic versioning) [org.eclipse.leshan:leshan-core:jar:1.1.0-SNAPSHOT]
[INFO] 
[INFO] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:

{
  "code": "java.class.externalClassExposedInAPI",
  "new": "class org.eclipse.leshan.core.request.BootstrapDiscoverRequest (archive = MavenArchive[gav=org.eclipse.leshan:leshan-core:jar:1.1.0-SNAPSHOT, file=\/home\/sbernard\/git\/leshan\/leshan-core\/target\/leshan-core-1.1.0-SNAPSHOT.jar], in api = true, through use = true)",
  "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
  /*
  Additionally, the following attachments can be used to further identify the difference:

  "classSimpleName": "BootstrapDiscoverRequest",
  "newArchive": "org.eclipse.leshan:leshan-core:jar:1.1.0-SNAPSHOT",
  "exampleUseChainInNewApi": "org.eclipse.leshan.core.request.BootstrapDiscoverRequest is used as parameter in method void org.eclipse.leshan.server.californium.request.LwM2mResponseBuilder<T extends org.eclipse.leshan.core.response.LwM2mResponse>::visit(org.eclipse.leshan.core.request.BootstrapDiscoverRequest) (method void org.eclipse.leshan.server.californium.request.LwM2mResponseBuilder<T extends org.eclipse.leshan.core.response.LwM2mResponse>::visit(org.eclipse.leshan.core.request.BootstrapDiscoverRequest) is part of the API)",
  "package": "org.eclipse.leshan.core.request",
  "classQualifiedName": "org.eclipse.leshan.core.request.BootstrapDiscoverRequest",
  "elementKind": "class",
  */
},
```
I understand this is considering as a warning, so this should maybe not break the build ("breaks semantic versioning"), but eventually just display a warning ? 

I also tried the recommended `mvn package revapi:update-versions` but this not solve the issue. (it partially increase the minor version and still complain about the same issue)

(I know how to ignore this error, I just want to ensure that I really get the error and be sure that the behavior of revapi is the expected one)

**Comment by metlos** [comment]
> I never get any complains about revapi.
>
> And recently I add a new class in core (in a minor version) which is exposed in 1 specific module. (all module have their minor version increased)
It seems that only the new addition is considered as a problem, I don't get why ?

Yes, the "external class exposed" is only reported for newly added or newly exposed classes. For things already exposed, "the damage is already done".

I do understand that it might come across as maybe too strong to break the build on these things, but on the other hand, if these problems pass by default, no one is ever going to notice ;)

And I do think that your usage of "core" classes in your "specific" modules' APIs is totally correct. In fact, revapi itself does the same thing.

Probably the easiest way of telling revapi that this is indeed intended and ok is to ignore these occurrences in a configuration inherited by all submodules, like for example: https://github.com/revapi/revapi/blob/89d78010432f9714d594adecdfd71c694fc569e1/revapi-build/pom.xml#L472

Notice that the rules are quite specific: They only ignore "external class exposed" for classes coming from "my" archives or archives that I consider part of the API by design even if they come from dependencies.

Would you care to summarize your experience/solution with this in an FAQ entry? I would really appreciate that.. https://github.com/revapi/revapi/blob/master/revapi-site/src/site/asciidoc/faq.adoc

**Comment by metlos** [comment]
Ah, I realized I didn't answer all your questions.

> I also tried the recommended mvn package revapi:update-versions but this not solve the issue. (it partially increase the minor version and still complain about the same issue)

Hmm... this is interesting... I see in your configuration, that you only allow non-breaking changes in the minor version bumps, so that would explain why the problem is still reported. At the same time `update-versions` considers all non-breaking and potentially-breaking changes to only require a minor version bump.

This calls for more thought :)

**Comment by metlos** [comment]
https://github.com/revapi/revapi/issues/190

**Comment by sbernard31** [comment]
> Probably the easiest way of telling revapi that this is indeed intended and ok is to ignore these occurrences in a configuration inherited by all submodules, like for example: 

I will do that thx a lot. 
Could it make sense if by default all sub-modules from the same maven project (maybe there is no way to do that)  or same groupid are ignored ?  
Or maybe you right this is something which just need a good F.A.Q and almost all user should face this issue and configure it in the right way for them.

> Yes, the "external class exposed" is only reported for newly added or newly exposed classes. For things already exposed, "the damage is already done".

Finally this looks like pretty much the same kind of error than [Class Is Non-Public Part of API](https://revapi.org/modules/revapi-java/differences.html#a_class_is_non_public_part_of_api)

But `Class Is Non-Public Part of API` is raised even for previous issue. Same argument could be used here : ""the damage is already done".  I just raised something which could be a kind of inconsistency.

> Would you care to summarize your experience/solution with this in an FAQ entry? I would really appreciate that.. https://github.com/revapi/revapi/blob/master/revapi-site/src/site/asciidoc/faq.adoc

I will try to find time to do that.

Thx again for your time :pray:

**Comment by sbernard31** [comment]
> Would you care to summarize your experience/solution with this in an FAQ entry? I would really appreciate that.. https://github.com/revapi/revapi/blob/master/revapi-site/src/site/asciidoc/faq.adoc

First try :  #191.

**Comment by metlos** [comment]
I think we've solved this, right? Thanks for the contribution to the FAQ. Greatly appreciated!

If I missed something feel free to re-open or file another issue.
