### ISSUE TITLE
Configuration should be specified in XML

### ISSUE THREAD

**Issue by metlos** [revapi/revapi#19]
at least the maven plugin should understand XML configuration instead of JSON. JSON looks ugly and out of place in `pom.xml`.

**Comment by MarianMacik** [comment]
Hi, @metlos,

we use revapi in droolsjbpm projects on GitHub. I would like to propose for using XML too because I have found adding comments to config files in JSON very painful. Although revapi can cope with /* comment */ comments, they are not allowed according to JSON spec and, moreover, GitHub will mark them as an issue. With larger changes and configurations, comments are essential for us and this is what XML provides out of the box. Consider adding this to revapi, please. Thanks!

Marian

**Comment by metlos** [comment]
Implemented in `revapi-maven-plugin-0.9.0`.
