### ISSUE TITLE
Support Java8

### ISSUE THREAD

**Issue by metlos** [revapi/revapi#2]

**Comment by mikhail-antonov** [comment]
Hi,

I'm trying to build 0.31 from source using 'mvn install' and getting following

[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.2.2:check (api-check) on project revapi-build: Execution api-check of goal org.revapi:revapi-maven-plugin:0.2.2:check failed: Unable to load the mojo 'check' in the plugin 'org.revapi:revapi-maven-plugin:0.2.2' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/revapi/maven/CheckMojo : Unsupported major.minor version 52.0

I'm using Oracle java 1.7.0_51.

Is it not supported?

**Comment by metlos** [comment]
On Wednesday, June 10, 2015 18:26:32 Mikhail Antonov wrote:
> Hi,
> 
> I'm trying to build 0.31 from source using 'mvn install' and getting
> following
> 
> [ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.2.2:check
> (api-check) on project revapi-build: Execution api-check of goal
> org.revapi:revapi-maven-plugin:0.2.2:check failed: Unable to load the mojo
> 'check' in the plugin 'org.revapi:revapi-maven-plugin:0.2.2' due to an API
> incompatibility:
> org.codehaus.plexus.component.repository.exception.ComponentLookupException
> : org/revapi/maven/CheckMojo : Unsupported major.minor version 52.0
> 
> I'm using Oracle java 1.7.0_51.
> 
> Is it not supported?
> 

I think since 0.2.something, Revapi itself requires Java8 to run. 0.3.x 
definitely requires Java8 to run.

As a workaoround, you can still build your jars for java7 using the java8 
compiler by setting up the maven compiler plugin and you can use animal 
sniffer to disallow using java8 features and APIs even if you're using java8 
to compile your code.

I.e. your maven build needs to run using java8 for it to be able to use 
revapi, but your resulting artifacts can still target and be safe to use in 
java7.

I have no plans to move back to being able to compile and run Revapi on Java7.

Hope that does not cause you too much trouble.

**Comment by mikhail-antonov** [comment]
Yeah, that's not really a big problem, just wanted to check if that's some mistake on my side or just by design:) Thanks for clarification!
