### ISSUE TITLE
Add support for Java 9

### ISSUE THREAD

**Issue by psiroky** [revapi/revapi#20]
I know Java 9 is far from final, but because I want to be a good Java citizen I am trying the EA builds with our projects to make sure they work as expected (and potentially report bugs if they don't).

Currently I am getting the following error from revapi:
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.4.1:report (report) on project kie-api: Execution report of goal org.revapi:revapi-maven-plugin:0.4.1:report failed: Failed to generate report. Failed to analyze archives: Failed to obtain class tree due to compilation failure. Compilation failed while analyzing API[...]:
[ERROR] warning: Supported source version 'RELEASE_8' from annotation processor 'org.revapi.java.compilation.ProbingAnnotationProcessor' less than -source '1.9'
```

It would be great if revapi could support Java 9.

**Comment by psiroky** [comment]
Argh, I forgot to specify the versions: `revapi-maven-plugin:0.4.1` + `revapi-java:0.6.0`.

**Comment by metlos** [comment]
Well, this is a biggie.
Revapi currently uses the java compiler to get at the models of the classes (there is a plan to change it and use javassist instead but that is far from complete).

To get at the model, Revapi hooks itself into the compilation using an annotation processor. The annotation processor has to be annotated with the supported source version otherwise java6 is assumed.

So I'd basically have to produce 2 versions of the java extension 1 for java8 and one for java9.

And even if that was done, java modules and the way the affect visibility of the classes would be ignored - adding support for analyzing java modules is another biggish piece of work.

But yes, this is of course on the long term radar - unfortunately I don't see an immediate quick fix that would allow to at least run the analysis (unless I'm mistaken about `@SupportedSourceVersion` semantics).

**Comment by metlos** [comment]
Huh, that was quick -  I think a quick fix is possible ;)

**Comment by psiroky** [comment]
Thanks for the quick response! I was basically just thinking about non-jigsaw JDK 9 builds. At least for now. Looking at the error message again, it mentions `-source '1.9'` which is bit weird, because we are for sure specifying 1.8, at least for maven-compiler-plugin. Could it perhaps be configured in revapi as well?

**Comment by metlos** [comment]
I've release `revapi-java-0.6.1` that should get you going. The only thing it does is that it should run with java9 - no java9 features, like modules or multi-target jars, are supported.

**Comment by psiroky** [comment]
This is what I was looking for. Just tested it and works like a charm. Thanks!
