### ISSUE TITLE
versionIncreaseAllows wrong for 0. semver case

### ISSUE THREAD

**Issue by Vampire** [revapi/revapi#216]
The documentation for `versionIncreaseAllows` at https://revapi.org/revapi-basic-features/semver-ignore.html#_properties says:
> if the major version is 0, breaking changes on minor release and non-breaking changes on patch release.

This is not correct.
If only the documentation is wrong, this is a doc bug, if the implementation also follows along it is also a code bug.

The semver specifcation at https://semver.org/#spec-item-4 says:
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

So for the `0.` case there are no restrictions whatsoever, neither for changing the patch version, nor for changing the minor version.

**Comment by metlos** [comment]
You are right. I would consider that a documentation bug though, because Revapi needs some default behavior for increasing/classifiying the version changes, so this is what I went with.

Would you mind creating a PR with the updated docs? https://github.com/revapi/revapi/edit/master/revapi-basic-features/src/site/modules/ROOT/pages/semver-ignore.adoc

**Comment by metlos** [comment]
Note that now there is a new `revapi.versions` extension that honors semver in this regard - in 0.x.y anything is allowed even in patch releases. https://revapi.org/revapi-basic-features/0.12.0/versions.html
