### ISSUE TITLE
Immutables generate false-positive warnings

### ISSUE THREAD

**Issue by thiagofabre** [revapi/revapi#218]
For some reason, the revapi is raising false-positive  warninigs about Immutables annotations ( https://immutables.github.io )
Did anyone face this issue?

![Screenshot from 2020-11-02 15-33-21](https://user-images.githubusercontent.com/6961049/97886724-dc78df00-1d20-11eb-94e3-91ba3fc982c4.png)

**Comment by metlos** [comment]
Because annotating the fields/methods might have semantic consequences (that Revapi doesn't know about), like different bytecode generated, different DB schema created, etc.), it by default flags changes in annotations as potentially breaking the semantics.

You can configure Revapi to ignore these (see https://revapi.org/revapi-java/differences.html#_annotation_removed_java_annotation_removed and https://revapi.org/revapi-basic-features/differences.html):

```xml
<revapi.differences>
  <ignore>true</ignore>
  <differences>
    <item>
      <code>java.annotation.removed</code>
      <annotationType>org.immutables.value.Value.Default</annotationType>
      <justification>...</justification>
    </item>
  </differences>
</revapi.differences>
```
I would appreciate any PR improving the docs if you find them lacking/unclear in some regard.

**Comment by thiagofabre** [comment]
Thanks for your answer. 
We did some testing here and now it's working fine!!
