### ISSUE TITLE
RevApi hangs on small jar analysis

### ISSUE THREAD

**Issue by targeter21** [revapi/revapi#223]
Hi, I was trying to analyze a 68KB jar and RevApi seems to hang endlessly. Here is my code which is largely the getting started code using `0.23.2` of `revapi-java`:

JDK 11:
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

Code:
```
final Revapi revapi = Revapi.builder()
        .withAnalyzers(JavaApiAnalyzer.class)
        .build();

    final File file1 = new File("path_to_jar/fundamentals-reflection_2.12-0.9.5-M14.jar");
    final File file2 = new File("path_to_jar/fundamentals-reflection_2.12-1.0.2.jar");

    final AnalysisContext analysisContext = AnalysisContext.builder()
        .withOldAPI(API.of(new FileArchive(file1)).build())
        .withNewAPI(API.of(new FileArchive(file2)).build())
        .build();

    AnalysisResult analyzeResult = revapi.analyze(analysisContext);
    analyzeResult.close();
 ```

Stack trace when paused in the IDE:
```
park:-1, Unsafe (jdk.internal.misc)
park:194, LockSupport (java.util.concurrent.locks)
parkAndCheckInterrupt:885, AbstractQueuedSynchronizer (java.util.concurrent.locks)
doAcquireSharedInterruptibly:1039, AbstractQueuedSynchronizer (java.util.concurrent.locks)
acquireSharedInterruptibly:1345, AbstractQueuedSynchronizer (java.util.concurrent.locks)
await:232, CountDownLatch (java.util.concurrent)
get:56, CompilationFuture (org.revapi.java.compilation)
get:29, CompilationFuture (org.revapi.java.compilation)
waitForCompilation:103, JavaElementForest (org.revapi.java.model)
stream:85, JavaElementForest (org.revapi.java.model)
prune:129, JavaArchiveAnalyzer (org.revapi.java)
analyzeAndPrune:390, Revapi (org.revapi)
analyzeWith:302, Revapi (org.revapi)
analyze:202, Revapi (org.revapi)
main:25, App
```
 
 I'm new to RevApi, but it seems strange to see it hang on what I'd expect to be a quick comparison when I've been able to process jars much larger than that without fail. Many thanks for all the work so far!

**Comment by metlos** [comment]
In your example you're not adding any reporter extension so you won't be able to collect the analysis results.

Am I right that you're trying to analyze this https://mvnrepository.com/artifact/io.7mind.izumi/fundamentals-reflection_2.12/1.0.2 ? I'll try locally and see what I get...

**Comment by metlos** [comment]
Hmm... This is Scala... I do know that Revapi can have very bad perf with Scala because it tries to deduce FQN from the binary name of the classes... Because Scala uses a lot of `$` in names of its generated classes this is a very slow process because Revapi needs to make a lot of tries before it figures out what the class name actually is...

This is going to get better in the future when I don't use the java compiler for the analysis and will be able to use the binary name directly to find the class in question...

**Comment by metlos** [comment]
I've played with this and actually hopefully made some slight optimizations, but still - look at that class name :)

```
13:02:55.178 TRACE izumi.fundamentals.reflection.macrortti.LightTypeTag$TraitPickler$macro$1$1$Pickler$macro$21$1$TraitPickler$macro$22$1$Pickler$macro$23$1$Pickler$macro$33$1$TraitPickler$macro$34$1$Pickler$macro$36$1$: 365 lookups to failure.
```

This trace log tells me that there were 365 valid "dottings" of the above binary name (such that it gives a valid FQN of a non-anonymous class), all of which Revapi had to try and lookup just in case there indeed was a class like that. And all that for nothing because, indeed, this was an anonymous class in the end...

I wish I knew of a way to figure out a FQN of a class given just its binary name that would be fast and didn't require reading the class file...

**Comment by metlos** [comment]
Let's slot this under #234.
