### ISSUE TITLE
add support for @Deprecated in revapi?

### ISSUE THREAD

**Issue by monperrus** [revapi/revapi#83]
It would makes sense that when one removes a `@Deprecated` class or method, this is not considered as breaking.

How to do this?

**Comment by metlos** [comment]
This could be achieved using a custom `DifferenceTransform`. I don't think it is possible out of the box and I am not sure I would want that as a default behavior.

Basically, you would have to create a new Revapi extension jar with your implementation of `DifferenceTransform` interface and put it down as a dependency of the revapi maven plugin.

See for example https://github.com/revapi/revapi/blob/master/revapi-java/src/main/java/org/revapi/java/transforms/methods/AnnotationTypeAttributeRemoved.java where a "java.method.removed" is transformed into a different problem code when the method in question is in fact an annotation attribute.

Your impl would be quite similar. You would also transform the "java.method.removed" problem code and would check if the old element had a \@Deprecated annotation on it. If yes, you would return `null`, which means you want the difference discarded, otherwise you would just return the original difference.

A short intro into how to build a new extension can be found here: http://revapi.org/modules/revapi-java/enhance-java-checks.html

**Comment by monperrus** [comment]
> I would want that as a default behavior. 
This may be an option.

**Comment by metlos** [comment]
K, you persuaded me 😄 
I'll add a new code - `java.method.deprecatedRemoved` which by default will be classified the same as `java.method.removed`. When there is a code you can then use the `revapi.reclassify` configuration to reclassify it any way you wish...

Would that be OK for you?

**Comment by metlos** [comment]
When I'm at it, I should also add such codes for classes and fields...

**Comment by monperrus** [comment]
> I'll add a new code - |java.method.deprecatedRemoved| which by default will be classified the same
> as |java.method.removed|. When there is a code you can then use the |revapi.reclassify|
> configuration to reclassify it any way you wish...
>
> Would that be OK for you?
>
Yes, thanks.

**Comment by metlos** [comment]
Hi, just to let you know I didn't forget about this.. :-) When adding the code I decided this is not worth "polluting" the change codes with a variant specific to one type of removal.. Others use `@Beta` or `@Internal` or lack of `@Public` to designate unstable parts of API for which the proposed solution wouldn't work.

So instead I've been working on the revamping of filtering/matching that will make it possible to express stuff like "method annotated with `@Deprecated` that has been removed". It just takes much longer than I expected with the life intervening in unexpected ways :-)

**Comment by monperrus** [comment]
Supporting @Beta / @Internal / @Unstable or lack of @Public will be 
super useful, thanks!

**Comment by metlos** [comment]
Closing in favor of #17 which should solve this.
